$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: blue
endpoint_name: amazon-review-endpoint

model: azureml:amazon-review-sentiment-model:1

code_configuration:
  code: ../src
  scoring_script: score.py

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
  conda_file: ../env/inference_conda.yml

instance_type: Standard_DS3_v2
instance_count: 1
