$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

display_name: phase2_random_forest_training
experiment_name: phase2_training_experiment

code: ..

command: >-
  python src/train.py
  --input_data ${{inputs.training_data}}
  --output_dir ${{outputs.model_output}}

inputs:
  training_data:
    type: uri_file
    path: ../phase2/data/session_dataset_safe.csv

outputs:
  model_output:
    type: uri_folder

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: ../env/conda.yml

compute: azureml:cpu-cluster
